version: "3.8"

services:
  postgres:
    image: postgres:15.15-trixie
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    networks:
      - image-manager

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - ./db/rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - image-manager

  image-manager:
    image: image-manager
    container_name: image-manager
    ports:
      - "${PORT}:4000"
    volumes:
      - ./db/image-manager_data:/var/lib/image-manager
    networks:
      - image-manager

networks:
  image-manager:
    driver: bridge

